version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      # - "28080:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=serverless
      - DATA_DIR=/tmp/localstack/data
    volumes:
          - '/private/tmp/localstack:/tmp/localstack'